import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { useState, useEffect } from 'react';
import "./globals.css";

import Footer from '@/component/Footer'
import Header from '@/component/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  
  // const [cart, setCart] = useState<Product[]>([]);
  // const [showCart, setShowCart] = useState(false);
  // const [showNotification, setShowNotification] = useState(false);
  // const [notificationProgress, setNotificationProgress] = useState(100);
  

  // const addToCart = (product: Product) => {
  //   setCart([...cart, product]);
  //   setShowNotification(true);
  //   setNotificationProgress(100);
  // };

  // const removeFromCart = (productId: number) => {
  //   setCart(cart.filter(item => item.id !== productId));
  // };

  // const totalItems = cart.length;
  // const totalPrice = cart.reduce((sum, item) => sum + item.price, 0);
  
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
      {/* <Header 
        cartItemCount={totalItems} 
        onCartClick={() => setShowCart(!showCart)} 
      /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
